#!/bin/sh
# XDM session for GNOME on NetBSD.

PATH="/usr/pkg/bin:/usr/pkg/sbin:/usr/X11R7/bin:/usr/bin:/bin"
export PATH

# Required/recommended by pkgsrc GNOME/mutter on NetBSD.
XCURSOR_PATH="/usr/pkg/share/icons"
export XCURSOR_PATH

# Swedish keyboard layout for X11.
setxkbmap se

exec gnome-session
