"""Render classified decisions as an edited config or a maintainable overlay."""

from __future__ import annotations

import difflib
from collections import defaultdict

from more_itertools import unique_everseen

from .models import AttachmentRule, Decision


def render_comment_style(
    source: str,
    decisions: list[Decision],
    *,
    remove: bool = False,
    comment_prefix: str = "# adjustkernel-ng: absent: ",
) -> str:
    """Preserve source text and comment/drop only confidently absent rules."""

    by_line = {d.rule.line_no: d for d in decisions}
    output: list[str] = []

    for line_no, line in enumerate(source.splitlines(keepends=True), start=1):
        decision = by_line.get(line_no)
        if decision is None or decision.action == "keep":
            output.append(line)
            continue
        if remove:
            continue

        indentation = line[: len(line) - len(line.lstrip())]
        body = line[len(indentation) :]
        output.append(f"{indentation}{comment_prefix}{body}")

    return "".join(output)


def render_overlay_style(
    include_path: str,
    rules: list[AttachmentRule],
    decisions: list[Decision],
    *,
    version: str,
) -> str:
    """Generate ``include`` + ``no ...`` delta configuration.

    config(5) states that ``no instance at attachment`` removes all matching
    instances that differ only in locator values.  If a group contains *any*
    rule we need to keep, no negation for that group is emitted.
    """

    grouped: dict[tuple[str, str], list[Decision]] = defaultdict(list)
    for decision in decisions:
        grouped[decision.rule.key_without_locators].append(decision)

    safe_no_statements: list[str] = []
    suppressed: list[AttachmentRule] = []

    for (instance, attachment), group in grouped.items():
        if any(d.action == "keep" for d in group):
            suppressed.extend(d.rule for d in group if d.action == "disable")
            continue
        if all(d.action == "disable" for d in group):
            safe_no_statements.append(f"no {instance} at {attachment}")

    safe_no_statements = list(unique_everseen(safe_no_statements))

    out = [
        f"# Generated by adjustkernel-ng {version}.\n",
        "# Review after hardware changes and major NetBSD upgrades.\n",
        "# NetBSD config(1), not this program, is the final syntax authority.\n\n",
        f'include "{include_path}"\n\n',
        "# Attachment rules absent from the observed runtime device tree.\n",
    ]
    out.extend(f"{statement}\n" for statement in safe_no_statements)
    if not safe_no_statements:
        out.append("# (none)\n")

    if suppressed:
        out.append(
            "\n# Candidate removals suppressed: locator-insensitive 'no' would also\n"
            "# remove a retained rule with the same instance/attachment pair.\n"
        )
        out.extend(
            f"# source line {rule.line_no}: {rule.instance} at {rule.attachment}\n"
            for rule in suppressed
        )

    return "".join(out)


def unified_diff(old: str, new: str, *, old_name: str, new_name: str) -> str:
    """Return a standard unified diff for review."""

    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=old_name,
            tofile=new_name,
        )
    )
